version: 2
updates:
  # Manage Git submodules.
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: daily
      # Check for updates at 7am UTC.
      time: "07:00"
    commit-message:
      prefix: "submodules:"
    labels:
      - c:deps

  # Manage Github Actions versions.
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "ci:"
